; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
    
    #include "p16f628a.inc"

; CONFIG
; __config 0xFF70
 __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF
 
 
#define BANK0		    BCF STATUS,RP0
#define BANK1		    BSF STATUS,RP0
 
    CBLOCK  0X20
	FILTRO
	FLAGS
	TEMPO1
	TEMPO2
	TEMPO3
	TEMPO4
    ENDC
    
;variaveis
#define JA_LI		    FLAGS,0    
    
;entradas
#define	BOT_LIGA1	    PORTA,1
#define	BOT_LIGA2	    PORTA,2
#define	BOT_DESLIGA	    PORTA,3
    
#define	LAMPADA		    PORTA,0
    
;constantes
V_FILTRO    equ	.100

V_TEMPO1    equ	.110
V_TEMPO2    equ	.110
V_TEMPO3    equ	.150
V_TEMPO4    equ	.150
    
RES_VECT  CODE    0x0000            ; processor reset vector

    BANK1
    BCF		TRISA,0
    BANK0
    MOVLW	V_FILTRO		    
    MOVWF	FILTRO		    
    BCF		JA_LI		    
    
LOOP
    BTFSS	BOT_LIGA1		    
    GOTO	LIGA1_ACIONADO	    
    BTFSS	BOT_LIGA2		    
    GOTO	LIGA2_ACIONADO	    
    GOTO	LOOP		    
    
LIGA1_ACIONADO
    BTFSC	JA_LI		    
    GOTO	LOOP		    
    DECFSZ	FILTRO,F		    
    GOTO	LOOP		    
    BSF		JA_LI		    
    GOTO	PISCA2HZ_LED	    
    
LIGA2_ACIONADO
    BTFSC	JA_LI		    
    GOTO	LOOP		    
    DECFSZ	FILTRO,F		    
    GOTO	LOOP		    
    BSF		JA_LI		    
    GOTO	PISCA5HZ_LED	    
    
PISCA5HZ_LED
    CALL	DEVE_DESLIGAR
    BSF		LAMPADA
    CALL	ESPERAR_500MS
    BCF		LAMPADA
    CALL	ESPERAR_500MS
    GOTO	PISCA5HZ_LED
    
ESPERAR_500MS
    CALL	DEVE_DESLIGAR
    MOVLW	V_TEMPO1
    MOVWF	TEMPO1
    
INICIALIZA_TEMPO2
    MOVLW	V_TEMPO2
    MOVWF	TEMPO2
    
DEC_TEMPO2
    CALL	DEVE_DESLIGAR
    DECFSZ	TEMPO2,F
    GOTO	DEC_TEMPO2
    
DEC_TEMPO1
    DECFSZ	TEMPO1,F
    GOTO	INICIALIZA_TEMPO2
    RETURN
    
PISCA2HZ_LED
    CALL	DEVE_DESLIGAR
    BSF		LAMPADA
    CALL	ESPERAR_100MS
    BCF		LAMPADA
    CALL	ESPERAR_100MS
    GOTO	PISCA2HZ_LED
    
ESPERAR_100MS
    CALL	DEVE_DESLIGAR
    MOVLW	V_TEMPO3
    MOVWF	TEMPO3
    
INICIALIZA_TEMPO4
    MOVLW	V_TEMPO4
    MOVWF	TEMPO4
    
DEC_TEMPO4
    CALL	DEVE_DESLIGAR
    DECFSZ	TEMPO4,F
    GOTO	DEC_TEMPO4
    
DEC_TEMPO3
    DECFSZ	TEMPO3,F
    GOTO	INICIALIZA_TEMPO4
    RETURN
    
DEVE_DESLIGAR
    BTFSS	BOT_DESLIGA
    GOTO	DESLIGA_LED
    RETURN
    
DESLIGA_LED
    BCF		LAMPADA
    MOVLW	V_FILTRO		    
    MOVWF	FILTRO		    
    BCF		JA_LI		    
    GOTO	LOOP
    
    END    
